/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all users with optional filters */
    get: operations["findAll"];
    put?: never;
    /** Create a new user */
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}/unlock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unlock a user account */
    post: operations["unlock"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lock a user account */
    post: operations["lock"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}/enable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enable a user account */
    post: operations["enable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}/disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disable a user account */
    post: operations["disable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/otp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate OTP for a given email and purpose */
    post: operations["request"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/otp/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify the OTP for a given email and purpose */
    post: operations["verify"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign out the current user */
    post: operations["signout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate a user */
    post: operations["signin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/exists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Check if a user exists by email */
    post: operations["userExists"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/access-applications/{id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject an access application */
    post: operations["reject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/access-applications/{id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve an access application */
    post: operations["approve"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/access-applications/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a new access application */
    post: operations["submit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update role of a specific user */
    patch: operations["updateRole"];
    trace?: never;
  };
  "/v1/users/me/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update profile of current user */
    patch: operations["updateProfile"];
    trace?: never;
  };
  "/v1/users/me/org-communication": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update organization communication preference */
    patch: operations["updateOrgCommunicationOptIn"];
    trace?: never;
  };
  "/v1/users/me/marketing-updates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update marketing updates preference for current user */
    patch: operations["updateMarketingUpdatesOptIn"];
    trace?: never;
  };
  "/v1/users/me/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update email of current user */
    patch: operations["updateEmail"];
    trace?: never;
  };
  "/v1/users/me/account-activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update account activity notification preference */
    patch: operations["updateAccountActivityOptIn"];
    trace?: never;
  };
  "/v1/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a user by ID */
    get: operations["get"];
    put?: never;
    post?: never;
    /** Delete a specific user */
    delete: operations["delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current authenticated user */
    get: operations["getSelf"];
    put?: never;
    post?: never;
    /** Delete current authenticated user */
    delete: operations["deleteSelf"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export current user data as JSON */
    get: operations["export"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/access-applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all access applications with filtering and pagination */
    get: operations["findAll_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/access-applications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an access application */
    get: operations["get_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove OAuth provider from current user */
    delete: operations["removeAuthProvider"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateUserRequest: {
      /** Format: email */
      email: string;
      firstName: string;
      lastName: string;
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
    };
    UserMinimalResponse: {
      /** Format: email */
      email: string;
      providers: ("email" | "google")[];
      firstName: string;
      lastName?: string;
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
      avatarUrl?: string;
      orgCommunicationOptIn: boolean;
      accountActivityOptIn: boolean;
      marketingUpdatesOptIn: boolean;
    };
    OtpRequest: {
      /** Format: email */
      email: string;
      /** @enum {string} */
      purpose: "auth" | "change-email" | "remove-oauth-provider" | "export-data" | "delete-self";
    };
    OtpResponse: {
      message: string;
      /** Format: int64 */
      cooldown: number;
    };
    VerifyOtpRequest: {
      /** Format: email */
      email: string;
      /** @enum {string} */
      purpose: "auth" | "change-email" | "remove-oauth-provider" | "export-data" | "delete-self";
      otp: string;
    };
    SignupRequest: {
      firstName: string;
      lastName: string;
      /** Format: email */
      email: string;
    };
    SignInRequest: {
      /** Format: email */
      email: string;
    };
    UserExistenceRequest: {
      /** Format: email */
      email: string;
    };
    ExistenceResponse: {
      exists: boolean;
    };
    AccessApplicationRequest: {
      firstName: string;
      lastName: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
      reason: string;
    };
    UpdateRoleRequest: {
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
    };
    UpdateProfileRequest: {
      firstName: string;
      lastName?: string;
      avatarUrl?: string;
    };
    OptInRequest: {
      optIn: boolean;
    };
    UpdateEmailRequest: {
      /** Format: email */
      email: string;
    };
    PagedResponseUserResponse: {
      content: components["schemas"]["UserResponse"][];
      /** Format: int32 */
      pageNumber: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int32 */
      totalPages: number;
      first: boolean;
      last: boolean;
    };
    UserResponse: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      providers: ("email" | "google")[];
      firstName: string;
      lastName?: string;
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
      avatarUrl?: string;
      emailVerified: boolean;
      enabled: boolean;
      locked: boolean;
      orgCommunicationOptIn: boolean;
      accountActivityOptIn: boolean;
      marketingUpdatesOptIn: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserAccessExport: {
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
      providers: ("email" | "google")[];
    };
    UserDataExport: {
      identity: components["schemas"]["UserIdentityExport"];
      status: components["schemas"]["UserStatusExport"];
      access: components["schemas"]["UserAccessExport"];
      preferences: components["schemas"]["UserPreferenceExport"];
      timestamps: components["schemas"]["UserTimestampExport"];
    };
    UserExportResponse: {
      /** Format: date-time */
      exportedAt: string;
      schemaVersion: string;
      userData: components["schemas"]["UserDataExport"];
      notice: string;
    };
    UserIdentityExport: {
      /** Format: uuid */
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      avatarUrl: string;
    };
    UserPreferenceExport: {
      orgCommunicationOptIn: boolean;
      accountActivityOptIn: boolean;
      marketingUpdatesOptIn: boolean;
    };
    UserStatusExport: {
      enabled: boolean;
      emailVerified: boolean;
      locked: boolean;
    };
    UserTimestampExport: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AccessApplicationResponse: {
      /** Format: uuid */
      id: string;
      firstName: string;
      lastName: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "super-admin" | "admin" | "moderator" | "user";
      reason: string;
      /** @enum {string} */
      status: "approved" | "pending" | "rejected";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PagedResponseAccessApplicationResponse: {
      content: components["schemas"]["AccessApplicationResponse"][];
      /** Format: int32 */
      pageNumber: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int32 */
      totalPages: number;
      first: boolean;
      last: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  findAll: {
    parameters: {
      query?: {
        query?: string;
        role?: "super-admin" | "admin" | "moderator" | "user";
        enabled?: boolean;
        locked?: boolean;
        "email-verified"?: boolean;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PagedResponseUserResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  unlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  enable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  disable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  request: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["OtpResponse"];
        };
      };
    };
  };
  verify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyOtpRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  userExists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserExistenceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ExistenceResponse"];
        };
      };
    };
  };
  reject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  approve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  submit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessApplicationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoleRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  updateOrgCommunicationOptIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OptInRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  updateMarketingUpdatesOptIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OptInRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  updateEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateEmailRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  updateAccountActivityOptIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OptInRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSelf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
  deleteSelf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  export: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserExportResponse"];
        };
      };
    };
  };
  findAll_1: {
    parameters: {
      query?: {
        query?: string;
        role?: "super-admin" | "admin" | "moderator" | "user";
        status?: "approved" | "pending" | "rejected";
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PagedResponseAccessApplicationResponse"];
        };
      };
    };
  };
  get_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AccessApplicationResponse"];
        };
      };
    };
  };
  removeAuthProvider: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: "email" | "google";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserMinimalResponse"];
        };
      };
    };
  };
}
